package com.example.shishu_sneh_healthcare.presentation.report

import android.content.Context
import android.content.Intent
import android.graphics.*
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

object PdfReportGenerator {

    fun generateReport(
        context: Context,
        babyName: String,
        ageText: String,
        latestWeight: String,
        latestHeight: String,
        vaccineSummary: String,
        milestoneProgress: String,
        aiInsight: String
    ) {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(1080, 1920, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint()

        // ---------------------------------------------------
        // Background
        // ---------------------------------------------------
        canvas.drawColor(Color.parseColor("#FFF8FB"))

        // ---------------------------------------------------
        // Header
        // ---------------------------------------------------
        paint.color = Color.parseColor("#E91E63")
        paint.textSize = 52f
        paint.typeface = Typeface.create(Typeface.DEFAULT_BOLD, Typeface.BOLD)
        canvas.drawText("Shishu-Sneh Health Report", 60f, 100f, paint)

        // ---------------------------------------------------
        // Baby Section
        // ---------------------------------------------------
        drawSection(
            canvas,
            paint,
            "Baby Profile",
            listOf(
                "Name: $babyName",
                "Age: $ageText"
            ),
            180f
        )

        drawSection(
            canvas,
            paint,
            "Growth Summary",
            listOf(
                "Latest Weight: $latestWeight",
                "Latest Height: $latestHeight"
            ),
            450f
        )

        drawSection(
            canvas,
            paint,
            "Vaccination Status",
            listOf(vaccineSummary),
            720f
        )

        drawSection(
            canvas,
            paint,
            "Milestone Progress",
            listOf(milestoneProgress),
            990f
        )

        drawSection(
            canvas,
            paint,
            "AI Health Insight",
            listOf(aiInsight),
            1260f
        )

        // Footer
        paint.color = Color.GRAY
        paint.textSize = 28f
        canvas.drawText("Generated by Shishu-Sneh", 60f, 1800f, paint)

        document.finishPage(page)

        // ---------------------------------------------------
        // Save File
        // ---------------------------------------------------
        val file = File(context.getExternalFilesDir(null), "ShishuSneh_Report.pdf")
        document.writeTo(FileOutputStream(file))
        document.close()

        // ---------------------------------------------------
        // Open Share Intent
        // ---------------------------------------------------
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.provider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND)
        intent.type = "application/pdf"
        intent.putExtra(Intent.EXTRA_STREAM, uri)
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)

        context.startActivity(Intent.createChooser(intent, "Share Health Report"))
    }

    private fun drawSection(
        canvas: Canvas,
        paint: Paint,
        title: String,
        lines: List<String>,
        top: Float
    ) {
        val cardPaint = Paint()
        cardPaint.color = Color.WHITE
        cardPaint.setShadowLayer(8f, 0f, 4f, Color.LTGRAY)

        val rect = RectF(40f, top, 1040f, top + 220f)
        canvas.drawRoundRect(rect, 24f, 24f, cardPaint)

        paint.color = Color.parseColor("#E91E63")
        paint.textSize = 38f
        paint.typeface = Typeface.create(Typeface.DEFAULT_BOLD, Typeface.BOLD)
        canvas.drawText(title, 70f, top + 60f, paint)

        paint.color = Color.BLACK
        paint.textSize = 30f
        paint.typeface = Typeface.DEFAULT

        var y = top + 120f
        lines.forEach {
            canvas.drawText(it, 70f, y, paint)
            y += 45f
        }
    }
}